In [77]:
!pip install duckdb

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: duckdb in /home/tanmoy_chakraborty00001/.local/lib/python3.12/site-packages (1.4.3)

In [78]:
import duckdb

In [79]:
import os
os.getcwd()

'/home/tanmoy_chakraborty00001/data-engineering/Chapter02_SQL-Fundamentals'

In [80]:
!ls

Ex01_01_DDL_Basics.ipynb  README.md   run_sql.py  sales.duckdb
Ex01_01_DDL_Basics.sql	  duckdb.zip  sales.db

In [81]:
!ls data

ls: cannot access 'data': No such file or directory

In [82]:
conn = duckdb.connect(database=":memory:")

In [83]:
conn.execute("""CREATE TABLE SALES AS SELECT *
FROM read_csv_auto('/home/tanmoy_chakraborty00001/data/Sales-Export_2019-2020.csv');
""")

In [84]:
conn.execute("SELECT * FROM SALES LIMIT 10").df()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2020-02-12,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,2019-09-26,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,2019-07-11,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,2020-04-02,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,2019-12-22,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
5,Spain,"84,900.24",73701.90,2020-07-14,Clothing,"Farrell, Swaniawski and Crist",Emalia Dinse,Perri Aldersley,PC,60-6998932
6,Portugal,"71,620.08",62245.01,2019-02-05,Books,Schoen-Keeling,Celine Tumasian,Smitty Culverhouse,PC,69-6259390
7,UK,"156,585.22",126599.15,2020-08-30,Accessories,"Hermiston, Simonis and Wisoky",Jessamine Apark,Winny Agnolo,PC,64-5761908
8,Portugal,"78,461.13",63537.82,2020-05-10,Appliances,Hessel-Stiedemann,Celine Tumasian,Smitty Culverhouse,Mobile,91-4126746
9,France,"64,827.80",56043.63,2019-01-20,Appliances,Gislason-Stanton,Othello Bowes,Maighdiln Upcraft,PC,62-3312495

In [85]:
print(conn.execute("SELECT * FROM SALES LIMIT 10").fetchall())

[('Sweden', '17,524.02', 14122.61, datetime.date(2020, 2, 12), 'Books', 'Goldner-Dibbert', 'Maxie Marrow', 'Madelon Bront', 'Mobile', '70-0511466'), ('Finland', '116,563.40', 92807.78, datetime.date(2019, 9, 26), 'Games', 'Hilll-Vandervort', 'Hube Corey', 'Wat Bowkley', 'Mobile', '28-6585323'), ('Portugal', '296,465.56', 257480.34, datetime.date(2019, 7, 11), 'Clothing', 'Larkin-Collier', 'Celine Tumasian', 'Smitty Culverhouse', 'PC', '58-7703341'), ('Portugal', '74,532.02', 59752.32, datetime.date(2020, 4, 2), 'Beauty', 'Hessel-Stiedemann', 'Celine Tumasian', 'Aurelie Wren', 'PC', '14-6700183'), ('Spain', '178,763.42', 146621.76, datetime.date(2019, 12, 22), 'Games', 'Johns and Sons', 'Emalia Dinse', 'Bertha Walbrook', 'Tablet', '15-8765160'), ('Spain', '84,900.24', 73701.9, datetime.date(2020, 7, 14), 'Clothing', 'Farrell, Swaniawski and Crist', 'Emalia Dinse', 'Perri Aldersley', 'PC', '60-6998932'), ('Portugal', '71,620.08', 62245.01, datetime.date(2019, 2, 5), 'Books', 'Schoen-Keeling', 'Celine Tumasian', 'Smitty Culverhouse', 'PC', '69-6259390'), ('UK', '156,585.22', 126599.15, datetime.date(2020, 8, 30), 'Accessories', 'Hermiston, Simonis and Wisoky', 'Jessamine Apark', 'Winny Agnolo', 'PC', '64-5761908'), ('Portugal', '78,461.13', 63537.82, datetime.date(2020, 5, 10), 'Appliances', 'Hessel-Stiedemann', 'Celine Tumasian', 'Smitty Culverhouse', 'Mobile', '91-4126746'), ('France', '64,827.80', 56043.63, datetime.date(2019, 1, 20), 'Appliances', 'Gislason-Stanton', 'Othello Bowes', 'Maighdiln Upcraft', 'PC', '62-3312495')]

In [86]:
conn.execute("""SELECT * FROM SALES LIMIT 10""").df()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2020-02-12,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,2019-09-26,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,2019-07-11,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,2020-04-02,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,2019-12-22,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
5,Spain,"84,900.24",73701.90,2020-07-14,Clothing,"Farrell, Swaniawski and Crist",Emalia Dinse,Perri Aldersley,PC,60-6998932
6,Portugal,"71,620.08",62245.01,2019-02-05,Books,Schoen-Keeling,Celine Tumasian,Smitty Culverhouse,PC,69-6259390
7,UK,"156,585.22",126599.15,2020-08-30,Accessories,"Hermiston, Simonis and Wisoky",Jessamine Apark,Winny Agnolo,PC,64-5761908
8,Portugal,"78,461.13",63537.82,2020-05-10,Appliances,Hessel-Stiedemann,Celine Tumasian,Smitty Culverhouse,Mobile,91-4126746
9,France,"64,827.80",56043.63,2019-01-20,Appliances,Gislason-Stanton,Othello Bowes,Maighdiln Upcraft,PC,62-3312495

In [87]:
conn.execute("SELECT COUNT(*) FROM SALES").df()

   count_star()
0          1000

In [88]:
conn.execute("""SELECT COUNT(*) AS total_rows FROM sales""").df()

   total_rows
0        1000

In [89]:
conn.execute("SELECT * FROM sales LIMIT 10").df()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2020-02-12,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,2019-09-26,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,2019-07-11,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,2020-04-02,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,2019-12-22,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
5,Spain,"84,900.24",73701.90,2020-07-14,Clothing,"Farrell, Swaniawski and Crist",Emalia Dinse,Perri Aldersley,PC,60-6998932
6,Portugal,"71,620.08",62245.01,2019-02-05,Books,Schoen-Keeling,Celine Tumasian,Smitty Culverhouse,PC,69-6259390
7,UK,"156,585.22",126599.15,2020-08-30,Accessories,"Hermiston, Simonis and Wisoky",Jessamine Apark,Winny Agnolo,PC,64-5761908
8,Portugal,"78,461.13",63537.82,2020-05-10,Appliances,Hessel-Stiedemann,Celine Tumasian,Smitty Culverhouse,Mobile,91-4126746
9,France,"64,827.80",56043.63,2019-01-20,Appliances,Gislason-Stanton,Othello Bowes,Maighdiln Upcraft,PC,62-3312495

In [90]:
conn.execute("SHOW TABLES").df()

    name
0  SALES

In [97]:
conn.execute("DESCRIBE sales").df()

       column_name column_type null   key default extra
0          country     VARCHAR  YES  None    None  None
1  order_value_EUR     VARCHAR  YES  None    None  None
2             cost      DOUBLE  YES  None    None  None
3             date        DATE  YES  None    None  None
4         category     VARCHAR  YES  None    None  None
5    customer_name     VARCHAR  YES  None    None  None
6    sales_manager     VARCHAR  YES  None    None  None
7        sales_rep     VARCHAR  YES  None    None  None
8      device_type     VARCHAR  YES  None    None  None
9         order_id     VARCHAR  YES  None    None  None

In [98]:
conn.execute("PRAGMA table_info('sales')").df()

   cid             name     type  notnull dflt_value     pk
0    0          country  VARCHAR    False       None  False
1    1  order_value_EUR  VARCHAR    False       None  False
2    2             cost   DOUBLE    False       None  False
3    3             date     DATE    False       None  False
4    4         category  VARCHAR    False       None  False
5    5    customer_name  VARCHAR    False       None  False
6    6    sales_manager  VARCHAR    False       None  False
7    7        sales_rep  VARCHAR    False       None  False
8    8      device_type  VARCHAR    False       None  False
9    9         order_id  VARCHAR    False       None  False

In [101]:
conn.execute("""SELECT SUM(CAST(REPLACE(order_value_EUR, ',', '') AS DOUBLE)) AS total_sales_eur FROM SALES""").df()

   total_sales_eur
0     1.133617e+08

In [110]:
conn.execute("""SELECT category, SUM(CAST(REPLACE(order_value_EUR, ',', '') AS DOUBLE)) AS total_sales_eur FROM SALES GROUP BY category 
ORDER BY total_sales_eur DESC; """).df()

      category  total_sales_eur
0     Clothing      17661682.13
1        Games      15321623.45
2   Appliances      15139668.73
3  Electronics      14482077.62
4        Books      13179978.90
5       Beauty      12569063.88
6  Smartphones      11101654.66
7     Outdoors       5939075.44
8  Accessories       4703930.70
9        Other       3262983.20

In [120]:
conn.execute("""SELECT category, SUM(CAST(REPLACE(order_value_EUR, ',', '') AS DOUBLE)) AS Revenue, SUM(cost) AS Total_cost, 
SUM(CAST(REPLACE(order_value_EUR, ',', '') AS DOUBLE)) - SUM(cost) AS Profit FROM sales GROUP BY category ORDER BY Profit DESC;
""").df()

      category      Revenue   Total_cost      Profit
0     Clothing  17661682.13  14719744.04  2941938.09
1        Games  15321623.45  12761827.68  2559795.77
2   Appliances  15139668.73  12604789.39  2534879.34
3  Electronics  14482077.62  12080944.62  2401133.00
4        Books  13179978.90  10954065.02  2225913.88
5       Beauty  12569063.88  10450636.45  2118427.43
6  Smartphones  11101654.66   9281007.00  1820647.66
7     Outdoors   5939075.44   4882312.93  1056762.51
8  Accessories   4703930.70   3920034.37   783896.33
9        Other   3262983.20   2713949.49   549033.71